"use client";

import { useState } from "react";
import { Button } from "@/shared/components/Button";
import type { RoofDefinition } from "../types";

const systemTypes = ["tile","slate","sheet","membrane","asphalt","green","glazed","thatch","metal","concrete","other"];
const layerTypes = ["covering","protective_surface","waterproofing","underlay","separation_layer","batten","counter_batten","deck","sarking","insulation","vapour_control","air_barrier","structural_slab"];

export function RoofBuildUpsPanel({ definitions, saving, onCreate, onLayer }: { definitions: RoofDefinition[]; saving: boolean; onCreate: (payload: Record<string, unknown>) => Promise<void>; onLayer: (definitionId: string, payload: Record<string, unknown>) => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(""); const selected = definitions.find((item) => item.id === selectedId) || definitions[0] || null;
  const [draft, setDraft] = useState({ code: "", name: "", system_type: "tile", covering_material: "", default_waste_percent: 5 });
  const [layer, setLayer] = useState({ layer_type: "underlay", name: "", material: "", thickness_mm: "" });
  return <aside className="overflow-y-auto border-l border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-950">Roof build-ups</h3><p className="mt-1 text-xs leading-5 text-slate-500">One build-up can be assigned to many roof planes. Each layer becomes a traceable BOQ quantity.</p><div className="mt-4 space-y-2">{definitions.map((definition) => <button type="button" key={definition.id} onClick={() => setSelectedId(definition.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id === definition.id ? "border-blue-300 bg-blue-50" : "border-slate-200"}`}><p className="text-sm font-semibold">{definition.code ? `${definition.code} · ` : ""}{definition.name}</p><p className="mt-1 text-xs capitalize text-slate-500">{definition.system_type} · {definition.layers.length} layer(s)</p></button>)}</div>
    <details className="mt-5 border-t border-slate-200 pt-4" open={!definitions.length}><summary className="cursor-pointer text-sm font-semibold">Add roof build-up</summary><div className="mt-3 space-y-3"><Field label="Code" value={draft.code} onChange={(value) => setDraft({ ...draft, code: value })} /><Field label="Name" value={draft.name} onChange={(value) => setDraft({ ...draft, name: value })} /><label className="block"><span className="text-xs font-semibold uppercase text-slate-500">System type</span><select className="input mt-2 w-full" value={draft.system_type} onChange={(event) => setDraft({ ...draft, system_type: event.target.value })}>{systemTypes.map((value) => <option key={value}>{value}</option>)}</select></label><Field label="Covering material" value={draft.covering_material} onChange={(value) => setDraft({ ...draft, covering_material: value })} /><Button className="w-full" disabled={saving || !draft.name.trim()} onClick={() => void onCreate(draft)}>Save build-up</Button></div></details>
    {selected ? <details className="mt-5 border-t border-slate-200 pt-4"><summary className="cursor-pointer text-sm font-semibold">Layers in {selected.code || selected.name}</summary><div className="mt-3 space-y-2">{selected.layers.map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-xs"><strong>{item.layer_order}. {item.name}</strong><span className="mt-1 block capitalize text-slate-500">{item.layer_type.replaceAll("_", " ")}{item.thickness_mm ? ` · ${item.thickness_mm} mm` : ""}</span></div>)}</div><div className="mt-4 space-y-3"><label className="block"><span className="text-xs font-semibold uppercase text-slate-500">Layer type</span><select className="input mt-2 w-full" value={layer.layer_type} onChange={(event) => setLayer({ ...layer, layer_type: event.target.value })}>{layerTypes.map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><Field label="Layer name" value={layer.name} onChange={(value) => setLayer({ ...layer, name: value })} /><Field label="Material" value={layer.material} onChange={(value) => setLayer({ ...layer, material: value })} /><Field label="Thickness (mm)" value={layer.thickness_mm} onChange={(value) => setLayer({ ...layer, thickness_mm: value })} /><Button className="w-full" variant="secondary" disabled={saving || !layer.name.trim()} onClick={() => void onLayer(selected.id, { ...layer, layer_order: selected.layers.length + 1, thickness_mm: layer.thickness_mm ? Number(layer.thickness_mm) : null, measurement_unit: "m²", separate_boq_item: true })}>Add layer</Button></div></details> : null}
  </aside>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block"><span className="text-xs font-semibold uppercase text-slate-500">{label}</span><input className="input mt-2 w-full" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
