"use client";
import { useState, type PointerEvent as ReactPointerEvent } from "react";
import { centroid, zoneAreaM2 } from "@/features/demo/geometry";
import { useDemoStore } from "@/features/demo/store";
import type { BBox, Opening, Point, RoofZone, Wall, Zone } from "@/features/demo/types";
import { svgPoint } from "./DemoDrawing";

function colorForOpening(id:string){return useDemoStore.getState().openingFamilies.find(f=>f.id===id)?.color||"#2563eb"}
function colorForZone(z:Zone){const st=useDemoStore.getState();const f=z.kind==="floor"?st.floorFamilies.find(x=>x.id===z.familyId):st.ceilingFamilies.find(x=>x.id===z.familyId);return f?.color||"#3b82f6"}
function pointsAttr(ps:Point[]){return ps.map(p=>`${p.x},${p.y}`).join(" ")}

export function OpeningOverlays({viewportId,kind,hiddenFamilies=new Set<string>(),ghost=false}:{viewportId:string;kind?:"door"|"window";hiddenFamilies?:Set<string>;ghost?:boolean}){
 const allOpenings=useDemoStore(s=>s.openings); const openings=allOpenings.filter(o=>o.viewportId===viewportId&&(!kind||o.kind===kind)&&!hiddenFamilies.has(o.familyId)); const selected=useDemoStore(s=>s.selectedEntityId); const setSelected=useDemoStore(s=>s.setSelectedEntity); return <g opacity={ghost ? .34 : 1} pointerEvents={ghost?"none":undefined}>{openings.map(o=><OpeningBox key={o.id} opening={o} selected={!ghost&&selected===o.id} onSelect={()=>setSelected(o.id)}/>)}</g>;
}
function OpeningBox({opening,selected,onSelect}:{opening:Opening;selected:boolean;onSelect:()=>void}){const update=useDemoStore(s=>s.updateOpening);const captureUndo=useDemoStore(s=>s.captureGeometryUndo);const[hovered,setHovered]=useState(false);const[drag,setDrag]=useState<null|{type:"move"|"nw"|"ne"|"sw"|"se";start:Point;box:BBox}>(null);const b=opening.bbox;const c=colorForOpening(opening.familyId);function down(type:NonNullable<typeof drag>["type"],e:ReactPointerEvent<SVGElement>){const p=svgPoint(e as any);if(!p)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();setDrag({type,start:p,box:{...b}});onSelect();}function move(e:ReactPointerEvent<SVGElement>){if(!drag)return;const p=svgPoint(e as any);if(!p)return;const dx=p.x-drag.start.x,dy=p.y-drag.start.y;let {x,y,width,height}=drag.box;if(drag.type==="move"){x+=dx;y+=dy}else{if(drag.type.includes("w")){x+=dx;width-=dx}if(drag.type.includes("e"))width+=dx;if(drag.type.includes("n")){y+=dy;height-=dy}if(drag.type.includes("s"))height+=dy;}update(opening.id,{bbox:{x,y,width:Math.max(12,width),height:Math.max(12,height)}})}function up(){setDrag(null)}const handles=[{x:b.x,y:b.y,t:"nw"},{x:b.x+b.width,y:b.y,t:"ne"},{x:b.x,y:b.y+b.height,t:"sw"},{x:b.x+b.width,y:b.y+b.height,t:"se"}] as const;return <g onClick={e=>{e.stopPropagation();onSelect()}} onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)}><title>{opening.id}</title><rect x={b.x} y={b.y} width={b.width} height={b.height} fill={hovered?"#0ea5e9":c} fillOpacity={selected ? .18 : hovered?.22:.08} stroke={hovered?"#0284c7":c} strokeWidth={selected?5:hovered?4:3} vectorEffect="non-scaling-stroke" className="cursor-move" onPointerDown={e=>down("move",e)} onPointerMove={move} onPointerUp={up}/><text x={b.x+b.width+7} y={b.y+14} fontSize={15} fontWeight={800} fill={hovered?"#0284c7":c} paintOrder="stroke" stroke="white" strokeWidth={4}>{opening.familyId}</text>{selected?handles.map(h=><circle key={h.t} cx={h.x} cy={h.y} r={7} fill="white" stroke={c} strokeWidth={3} vectorEffect="non-scaling-stroke" onPointerDown={e=>down(h.t,e)} onPointerMove={move} onPointerUp={up}/>):null}</g>}

export function ZoneOverlays({kind,viewportId,hiddenFamilies=new Set<string>()}:{kind:"floor"|"ceiling";viewportId:string;hiddenFamilies?:Set<string>}){const allZones=useDemoStore(s=>kind==="floor"?s.floorZones:s.ceilingZones);const zones=allZones.filter(z=>z.viewportId===viewportId&&!hiddenFamilies.has(z.familyId));const selected=useDemoStore(s=>s.selectedEntityId);const setSelected=useDemoStore(s=>s.setSelectedEntity);return <>{zones.map(z=><ZoneShape key={z.id} zone={z} selected={selected===z.id} onSelect={()=>setSelected(z.id)}/>)}</>}
function ZoneShape({zone,selected,onSelect}:{zone:Zone;selected:boolean;onSelect:()=>void}){
 const update=useDemoStore(s=>s.updateZone),captureUndo=useDemoStore(s=>s.captureGeometryUndo),viewport=useDemoStore(s=>s.viewports.find(v=>v.id===zone.viewportId));
 type Drag=
  |{type:"move";start:Point;base:Point[];baseDeducts:Point[][];points:Point[];deducts:Point[][];pointerId:number}
  |{type:"vertex";index:number;points:Point[];pointerId:number};
 const[hovered,setHovered]=useState(false),[drag,setDrag]=useState<Drag|null>(null);
 const points=drag?.points||zone.points,deducts=drag?.type==="move"?drag.deducts:zone.deducts,c=colorForZone(zone),center=centroid(points),area=zoneAreaM2(points,deducts,viewport?.scaleMPerPx||.018);
 function move(e:ReactPointerEvent<SVGElement>){
  if(!drag||drag.pointerId!==e.pointerId)return;const point=svgPoint(e as any);if(!point)return;
  if(drag.type==="move"){
   const dx=point.x-drag.start.x,dy=point.y-drag.start.y;
   setDrag({...drag,points:drag.base.map(value=>({x:value.x+dx,y:value.y+dy})),deducts:drag.baseDeducts.map(deduct=>deduct.map(value=>({x:value.x+dx,y:value.y+dy})))});
  }else setDrag({...drag,points:drag.points.map((value,index)=>index===drag.index?point:value)});
 }
 function stop(e:ReactPointerEvent<SVGElement>){if(!drag||drag.pointerId!==e.pointerId)return;update(zone.kind,zone.id,drag.type==="move"?{points:drag.points,deducts:drag.deducts}:{points:drag.points});setDrag(null)}
 return <g onClick={e=>{e.stopPropagation();onSelect()}} onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)}><title>{zone.id}</title><polygon points={pointsAttr(points)} fill={hovered?"#0ea5e9":c} fillOpacity={selected?.34:hovered?.30:.20} stroke={selected?"#0f172a":hovered?"#0284c7":c} strokeWidth={selected?4:hovered?3.5:2.5} vectorEffect="non-scaling-stroke" className="cursor-move" onPointerDown={e=>{const point=svgPoint(e as any);if(!point)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();onSelect();const base=points.map(value=>({...value})),baseDeducts=deducts.map(deduct=>deduct.map(value=>({...value})));setDrag({type:"move",start:point,base,baseDeducts,points:base,deducts:baseDeducts,pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/><text x={center.x} y={center.y} textAnchor="middle" fontSize={15} fontWeight={800} fill="#0f172a" paintOrder="stroke" stroke="white" strokeWidth={4} pointerEvents="none">{zone.familyId} · {area.toFixed(1)} m²</text>{deducts.map((deduct,index)=><polygon key={index} points={pointsAttr(deduct)} fill="white" fillOpacity={.8} stroke="#ef4444" strokeDasharray="6 4" strokeWidth={2} vectorEffect="non-scaling-stroke" pointerEvents="none"/>)}{selected?points.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r={8} fill="white" stroke="#2563eb" strokeWidth={3} vectorEffect="non-scaling-stroke" className="cursor-crosshair" onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();setDrag({type:"vertex",index,points:points.map(value=>({...value})),pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/>):null}</g>
}

export function WallOverlays({viewportId,hiddenFamilies=new Set<string>()}:{viewportId:string;hiddenFamilies?:Set<string>}){const allWalls=useDemoStore(s=>s.walls);const walls=allWalls.filter(w=>w.viewportId===viewportId&&!hiddenFamilies.has(w.familyId));const selected=useDemoStore(s=>s.selectedEntityId);const setSelected=useDemoStore(s=>s.setSelectedEntity);return <>{walls.map(w=><WallLine key={w.id} wall={w} selected={selected===w.id} onSelect={()=>setSelected(w.id)}/>)}</>}
function WallLine({wall,selected,onSelect}:{wall:Wall;selected:boolean;onSelect:()=>void}){
 type Drag={type:"move";origin:Point;start:Point;end:Point;pointerId:number}|{type:"endpoint";end:"start"|"end";pointerId:number};
 const update=useDemoStore(s=>s.updateWall);const captureUndo=useDemoStore(s=>s.captureGeometryUndo);const viewport=useDemoStore(s=>s.viewports.find(v=>v.id===wall.viewportId));const[hovered,setHovered]=useState(false);const[drag,setDrag]=useState<Drag|null>(null);const st=useDemoStore.getState();const f=st.wallFamilies.find(x=>x.id===wall.familyId)!;const side1=st.wallFinishFamilies.find(x=>x.id===wall.side1Finish);const side2=st.wallFinishFamilies.find(x=>x.id===wall.side2Finish);const dx=wall.end.x-wall.start.x,dy=wall.end.y-wall.start.y,len=Math.max(1,Math.hypot(dx,dy));const nx=-dy/len,ny=dx/len;const thicknessPx=Math.max(5,(f.thicknessMm/1000)/(viewport?.scaleMPerPx||.018));const off=thicknessPx/2;
 const line=(p:Point,sign:number)=>({x:p.x+nx*off*sign,y:p.y+ny*off*sign});const a1=line(wall.start,1),b1=line(wall.end,1),a2=line(wall.start,-1),b2=line(wall.end,-1);
 function move(e:ReactPointerEvent<SVGElement>){if(!drag||drag.pointerId!==e.pointerId)return;const point=svgPoint(e as any);if(!point)return;if(drag.type==="move"){const dx=point.x-drag.origin.x,dy=point.y-drag.origin.y;update(wall.id,{start:{x:drag.start.x+dx,y:drag.start.y+dy},end:{x:drag.end.x+dx,y:drag.end.y+dy}})}else update(wall.id,{[drag.end]:point})}
 function stop(){setDrag(null)}
 return <g onClick={e=>{e.stopPropagation();onSelect()}} onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)}><title>{wall.id+" · "+f.description}</title><line x1={wall.start.x} y1={wall.start.y} x2={wall.end.x} y2={wall.end.y} stroke="transparent" strokeWidth={Math.max(18,thicknessPx+12)} vectorEffect="non-scaling-stroke" className="cursor-move" onPointerDown={e=>{const point=svgPoint(e as any);if(!point)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();onSelect();setDrag({type:"move",origin:point,start:{...wall.start},end:{...wall.end},pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/><line x1={wall.start.x} y1={wall.start.y} x2={wall.end.x} y2={wall.end.y} stroke={hovered?"#0ea5e9":f.color} strokeOpacity={hovered?.46:.30} strokeWidth={thicknessPx} vectorEffect="non-scaling-stroke" pointerEvents="none"/><line x1={a1.x} y1={a1.y} x2={b1.x} y2={b1.y} stroke={side1?.color||"#94a3b8"} strokeWidth={2} vectorEffect="non-scaling-stroke" pointerEvents="none"/><line x1={a2.x} y1={a2.y} x2={b2.x} y2={b2.y} stroke={side2?.color||"#94a3b8"} strokeWidth={2} vectorEffect="non-scaling-stroke" pointerEvents="none"/><line x1={wall.start.x} y1={wall.start.y} x2={wall.end.x} y2={wall.end.y} stroke={hovered?"#0284c7":f.color} strokeWidth={selected?5:hovered?4:2.5} strokeDasharray={f.classification==="External"?undefined:"8 5"} vectorEffect="non-scaling-stroke" pointerEvents="none"/>{selected||hovered||len>140?<text x={(wall.start.x+wall.end.x)/2} y={(wall.start.y+wall.end.y)/2-10} textAnchor="middle" fontSize={selected||hovered?14:11} fontWeight={800} fill={hovered?"#0284c7":f.color} paintOrder="stroke" stroke="white" strokeWidth={4} pointerEvents="none">{selected||hovered?`${f.mark} · ${(len*(viewport?.scaleMPerPx||.018)).toFixed(2)} m`:f.mark}</text>:null}{selected?(["start","end"] as const).map(end=>{const p=wall[end];return <circle key={end} cx={p.x} cy={p.y} r={8} fill="white" stroke={f.color} strokeWidth={3} vectorEffect="non-scaling-stroke" className="cursor-crosshair" onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();setDrag({type:"endpoint",end,pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/> }):null}</g>
}

export function RoofOverlays({viewportId,hiddenFamilies=new Set<string>()}:{viewportId:string;hiddenFamilies?:Set<string>}){const allZones=useDemoStore(s=>s.roofZones);const zones=allZones.filter(z=>z.viewportId===viewportId&&!hiddenFamilies.has(z.familyId));const selected=useDemoStore(s=>s.selectedEntityId);const setSelected=useDemoStore(s=>s.setSelectedEntity);return <>{zones.map(z=><RoofShape key={z.id} zone={z} selected={selected===z.id} onSelect={()=>setSelected(z.id)}/>)}</>}
function RoofShape({zone,selected,onSelect}:{zone:RoofZone;selected:boolean;onSelect:()=>void}){
 type Drag=
  |{type:"move";origin:Point;base:Point[];baseDeducts:Point[][];points:Point[];deducts:Point[][];pointerId:number}
  |{type:"vertex";index:number;points:Point[];pointerId:number};
 const update=useDemoStore(s=>s.updateRoofZone),captureUndo=useDemoStore(s=>s.captureGeometryUndo),viewport=useDemoStore(s=>s.viewports.find(v=>v.id===zone.viewportId)),st=useDemoStore.getState(),f=st.roofFamilies.find(x=>x.id===zone.familyId)!,u=st.upstandFamilies.find(x=>x.id===zone.upstandFamilyId)!;
 const[hovered,setHovered]=useState(false),[drag,setDrag]=useState<Drag|null>(null),points=drag?.points||zone.points,deducts=drag?.type==="move"?drag.deducts:zone.deducts,center=centroid(points),area=zoneAreaM2(points,deducts,viewport?.scaleMPerPx||.018);
 function move(e:ReactPointerEvent<SVGElement>){
  if(!drag||drag.pointerId!==e.pointerId)return;const point=svgPoint(e as any);if(!point)return;
  if(drag.type==="move"){
   const dx=point.x-drag.origin.x,dy=point.y-drag.origin.y;
   setDrag({...drag,points:drag.base.map(value=>({x:value.x+dx,y:value.y+dy})),deducts:drag.baseDeducts.map(deduct=>deduct.map(value=>({x:value.x+dx,y:value.y+dy})))});
  }else setDrag({...drag,points:drag.points.map((value,index)=>index===drag.index?point:value)});
 }
 function stop(e:ReactPointerEvent<SVGElement>){if(!drag||drag.pointerId!==e.pointerId)return;update(zone.id,drag.type==="move"?{points:drag.points,deducts:drag.deducts}:{points:drag.points});setDrag(null)}
 return <g onClick={e=>{e.stopPropagation();onSelect()}} onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)}><title>{zone.id}</title><polygon points={pointsAttr(points)} fill={hovered?"#0ea5e9":f.color} fillOpacity={selected?.32:hovered?.28:.18} stroke={selected?"#0f172a":hovered?"#0284c7":f.color} strokeWidth={selected?4:hovered?3.5:2.5} vectorEffect="non-scaling-stroke" className="cursor-move" onPointerDown={e=>{const point=svgPoint(e as any);if(!point)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();onSelect();const base=points.map(value=>({...value})),baseDeducts=deducts.map(deduct=>deduct.map(value=>({...value})));setDrag({type:"move",origin:point,base,baseDeducts,points:base,deducts:baseDeducts,pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/><text x={center.x} y={center.y} textAnchor="middle" fontSize={15} fontWeight={800} fill="#0f172a" paintOrder="stroke" stroke="white" strokeWidth={4} pointerEvents="none">{f.mark} · {area.toFixed(1)} m²</text>{deducts.map((deduct,index)=><polygon key={`d${index}`} points={pointsAttr(deduct)} fill="white" fillOpacity={.82} stroke="#ef4444" strokeWidth={2} strokeDasharray="6 4" vectorEffect="non-scaling-stroke" pointerEvents="none"/>)}{points.map((p,i)=>{const q=points[(i+1)%points.length],on=zone.upstandEdges[i]!==false;return <line key={`e${i}`} x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke={on?u.color:"#cbd5e1"} strokeWidth={on?8:4} strokeDasharray={on?undefined:"6 6"} vectorEffect="non-scaling-stroke" className="cursor-pointer" onClick={e=>{e.stopPropagation();captureUndo();const next=[...zone.upstandEdges];next[i]=!on;update(zone.id,{upstandEdges:next});onSelect()}}/>})}{selected?points.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r={8} fill="white" stroke="#2563eb" strokeWidth={3} vectorEffect="non-scaling-stroke" className="cursor-crosshair" onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);captureUndo();setDrag({type:"vertex",index,points:points.map(value=>({...value})),pointerId:e.pointerId})}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}/>):null}</g>
}
