export type Point = { x: number; y: number };
export type BBox = { x: number; y: number; width: number; height: number };
export type DemoStatus = "ready" | "confirmed" | "needs_review";
export type Sheet = { id:string; sheetNo:string; title:string; revision:string; image:string; page:number; included:boolean; width?:number; height?:number };
export type ViewportCategory = "plan"|"elevation"|"section"|"detail"|"schedule";
export type ScaleDistanceUnit = "m" | "cm" | "mm" | "ft-in";
export type ScaleCalibration = { printedScale:string; printedScaleLabel:string; printedEvidenceBox?:[number,number,number,number]; printedEvidenceSource:string; printedEvidenceLocation:string; printedEvidenceKind?:"printed"|"inherited"|"missing"; printedScaleInheritedFrom?:string; x:{line:[number,number,number,number];knownDistanceM:number;label:string;unit?:ScaleDistanceUnit;value?:string}; y:{line:[number,number,number,number];knownDistanceM:number;label:string;unit?:ScaleDistanceUnit;value?:string}; manualAxis?:"x"|"y"; notToScale?:boolean; printedScaleOnly?:boolean };
export type Viewport = { id:string; name:string; category:ViewportCategory; sheetId:string; bbox:[number,number,number,number]; parentViewportId?:string; order?:number; status:DemoStatus; scaleMPerPx?:number; calibration?:ScaleCalibration; takeoffElement?:"columns"|"beams"|"slab"; scopeRole?:string; connectedLevelRefs?:string[] };
export type Storey = { id:string; name:string; levelIndex:number; factor:number; heightM:number; status:DemoStatus };
export type OpeningFamily = { id:string; parent:"door"|"window"; mark:string; description:string; widthMm:number; heightMm:number; thicknessMm:number; material:string; fittings:string; source:string; color:string; frameMaterial?:string|null; leafMaterial?:string|null; glazing?:string|null; operation?:string|null; fireRating?:string|null; acousticRating?:string|null; finish?:string|null; sillHeightMm?:number|null; headHeightMm?:number|null; scheduledQuantity?:number|null; locationText?:string|null };
export type Opening = { id:string; familyId:string; kind:"door"|"window"; floorId:string; viewportId:string; bbox:BBox; hostWallId?:string; status:DemoStatus; locked?:boolean; confidence?:number|null; openingTag?:string|null; grossOpeningAreaM2?:number|null };
export type FinishFamily = { id:string; kind:"floor"|"ceiling"; mark:string; description:string; material:string; thicknessMm?:number; screed?:string; falls?:string; source:string; color:string };
export type Zone = { id:string; kind:"floor"|"ceiling"; familyId:string; floorId:string; viewportId:string; points:Point[]; deducts:Point[][]; room:string; status:DemoStatus; locked?:boolean };
export type FloorReviewRegion = { id:string; kind:"special"|"non_floor"|"obstruction"|string; name:string; classification:string; floorId:string; viewportId:string; points:Point[]; areaM2?:number|null; confidence?:number|null };
export type WallFamily = { id:string; mark:string; description:string; thicknessMm:number; classification:"External"|"Internal"|"Both"|"Unknown"; material:string; color:string; wallKind?:string; structuralRole?:string };
export type WallFinishFamily = { id:string; mark:string; description:string; material:string; thicknessMm:number; source:string; color:string; coverageMode?:string; coverageHeightMm?:number|null };
export type Wall = { id:string; familyId:string; floorId:string; viewportId:string; start:Point; end:Point; heightM:number; side1Finish:string; side2Finish:string; status:DemoStatus; locked?:boolean; lengthM?:number|null; grossAreaM2?:number|null; openingDeductionM2?:number|null; netAreaM2?:number|null; heightSource?:string; confidence?:number|null; wallKind?:string; classification?:string; side1FinishAreaM2?:number|null; side2FinishAreaM2?:number|null; finishFaces?:Array<{side:"A"|"B"; finishId:string; areaM2?:number|null; status?:string}> };
export type RoofFamily = { id:string; mark:string; description:string; layers:string; falls:string; source:string; color:string };
export type UpstandFamily = { id:string; mark:string; description:string; heightMm:number; source:string; color:string };
export type RoofZone = { id:string; familyId:string; upstandFamilyId:string; scope:"Terrace"|"Upper roof"; floorId:string; viewportId:string; points:Point[]; deducts:Point[][]; upstandEdges:boolean[]; status:DemoStatus; locked?:boolean; projectedAreaM2?:number|null; measuredAreaM2?:number|null; pitchDegrees?:number|null; roofType?:string; measurementStatus?:string; measuredUpstandM?:number|null; slabThicknessMm?:number|null; reinforcementKgM2?:number|null; soffitFormwork?:boolean; formedEdgeDepthMm?:number|null; structuralBasis?:string };
export type HeightRecord = { id:string; name:string; storeyId:string; viewportId:string; yTop:number; yBottom:number; heightM?:number; basis?:string; detected?:boolean; status:DemoStatus };
export type SlabRecord = { id:string; storeyId:string; viewportId:string; topY:number; bottomY:number; x0:number; x1:number; stepX:number; stepOffset:number; status:DemoStatus };
export type SpecificationItem = { id:string; name:string; category:string; topic?:string; viewportId:string; sheetId?:string; page?:number; bbox?:[number,number,number,number]; found:boolean; status:DemoStatus; rawText:string; columns?:string[]; rows?:string[][] };
export type ChatEvidence = { label:string; detail?:string; viewportId?:string; entityId?:string };
export type ChatMessage = {
  id:string;
  role:"assistant"|"user";
  text:string;
  entityId?:string;
  questionId?:string;
  evidence?:ChatEvidence[];
  action?:"evidence"|"item";
};
