"use client";
import { buildBoqRows, buildBoqState } from "@/features/demo/builders";
import { useDemoStore } from "@/features/demo/store";
import type { BoqDocumentSetup, BoqExport, BoqState, BoqTemplateItem, BoqTemplateLibrary, BoqTemplatePackage } from "./types";
import { NRM2_INFORMATION_REQUIRED } from "./nrm2";

let templatePackages:BoqTemplatePackage[]=[{id:"TPL-DEMO",name:"Quanto standard takeoff",description:"Demo quantity takeoff template",category:"Construction",version:1,is_default:true,is_builtin:true,is_active:true,items:[]}];
let selectedTemplateId="TPL-DEMO";
const sleep=(ms=160)=>new Promise(r=>setTimeout(r,ms));
export async function getBoqState(projectId:string,floorId:string|null,_groupingMode:string):Promise<BoqState>{ await sleep(80); const state=buildBoqState(projectId,floorId); return {...state,template:templatePackages.find(t=>t.id===selectedTemplateId)||templatePackages[0],templates:templatePackages}; }
export async function refreshBoq(_projectId:string,_groupingMode:string,_floorId:string|null){await sleep();return{ok:true};}
export async function addManualBoqRow(_projectId:string,payload:{description:string;section:string;item_code?:string|null;quantity:number;unit:string;rate?:number|null;floor_id:string|null;}){const st=useDemoStore.getState(); const id=`MAN-${Date.now()}`; const rate=payload.rate??null; st.addManualRow({id,floor_id:payload.floor_id,entity_type:"manual",section:payload.section,item_code:payload.item_code||null,description:payload.description,quantity:payload.quantity,unit:payload.unit,rate,amount:rate==null?null:payload.quantity*rate,status:"ready",source_ids:[],source_items:[],floor_ids:payload.floor_id?[payload.floor_id]:[],floor_names:[],missing_fields:[],manual:true,protected_description:false,protected_rate:false,excluded:false,sort_order:999});return{ok:true};}
export async function updateBoqRow(_projectId:string,rowId:string,payload:Record<string,unknown>){useDemoStore.getState().updateBoqOverride(rowId,payload);return{ok:true};}
export async function requestBoqExport(_projectId:string,format:"pdf"|"xlsx"|"csv"|"json",floorMode:string,floorId:string|null){const st=useDemoStore.getState(); const record:BoqExport={id:`EXP-${Date.now()}`,format,floor_mode:floorMode as BoqExport["floor_mode"],floor_id:floorId,filename:`Quanto-BOQ.${format}`,status:"ready",boq_version:1,template_version:1,setup_version:st.boqSetup.setup_version,created_at:new Date().toISOString()}; st.setExports([record,...st.exports]); await sleep(250); return {export:record};}
export async function getBoqExports(_projectId:string){return{exports:useDemoStore.getState().exports,active_jobs:[]};}

function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvEscape(v:unknown){const s=String(v??"");return /[,"\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
function makeCsv(){const rows=buildBoqRows();return "\uFEFF"+["Bill,Item,NRM2 Section,Description,Quantity,Unit,Rate,Amount",...rows.map(r=>[r.bill_no||"",r.boq_item_number||r.item_code||"",r.subcategory_code||"",r.description,r.quantity,r.unit,r.rate??"",r.amount??""].map(csvEscape).join(","))].join("\r\n");}
async function makeXlsx(){
  const ExcelJS=(await import("exceljs")).default;const workbook=new ExcelJS.Workbook();workbook.creator="Quanto";workbook.created=new Date();const rows=buildBoqRows();
  const style=(sheet:import("exceljs").Worksheet)=>{sheet.views=[{state:"frozen",ySplit:1}];sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1E3A8A"}};const keys=new Set(sheet.columns.map(column=>String(column.key||"")));if(keys.has("quantity"))sheet.getColumn("quantity").numFmt="0.000";if(keys.has("rate"))sheet.getColumn("rate").numFmt="#,##0.00";if(keys.has("amount"))sheet.getColumn("amount").numFmt="#,##0.00";sheet.pageSetup={paperSize:9,orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0};};
  const cover=workbook.addWorksheet("COVER");cover.getColumn(1).width=24;cover.getColumn(2).width=72;cover.mergeCells("A2:B2");cover.getCell("A2").value="BILL OF QUANTITIES";cover.getCell("A2").font={bold:true,size:20,color:{argb:"FF1E3A8A"}};cover.getCell("A4").value="Project";cover.getCell("B4").value="Quanto";cover.getCell("A5").value="Method";cover.getCell("B5").value="RICS NRM2 — Detailed measurement for building works";cover.getCell("A6").value="Currency";cover.getCell("B6").value=useDemoStore.getState().boqSetup.currency;cover.getCell("A7").value="Generated";cover.getCell("B7").value=new Date();cover.getCell("A9").value="Measurement basis";cover.getCell("B9").value="Confirmed takeoff records only. Unsupported work is listed on the Information Required sheet.";
  const summary=workbook.addWorksheet("MAIN SUMMARY");summary.columns=[{header:"Bill",key:"bill",width:12},{header:"Description",key:"description",width:50},{header:"Items",key:"items",width:12},{header:"Amount",key:"amount",width:22}];const bills=[...new Set(rows.map(r=>`${r.bill_no}|${r.bill_name}`))];bills.forEach(key=>{const [bill,name]=key.split("|");const group=rows.filter(r=>String(r.bill_no)===bill);summary.addRow({bill,description:name,items:group.length,amount:group.reduce((sum,r)=>sum+Number(r.amount||0),0)})});summary.addRow({description:"Grand total",amount:rows.reduce((sum,r)=>sum+Number(r.amount||0),0)});style(summary);
  bills.forEach(key=>{const [bill,name]=key.split("|");const sheet=workbook.addWorksheet(`BILL ${bill}`);sheet.columns=[{header:"Item",key:"item",width:18},{header:"NRM2 section",key:"section",width:22},{header:"Description",key:"description",width:72},{header:"Unit",key:"unit",width:10},{header:"Quantity",key:"quantity",width:15},{header:"Rate",key:"rate",width:18},{header:"Amount",key:"amount",width:20}];rows.filter(r=>String(r.bill_no)===bill).forEach(r=>sheet.addRow({item:r.boq_item_number,section:r.subcategory_code,description:r.description,unit:r.unit,quantity:r.quantity,rate:r.rate??"",amount:r.amount??""}));sheet.addRow({description:`Bill ${bill} — ${name} subtotal`,amount:rows.filter(r=>String(r.bill_no)===bill).reduce((sum,r)=>sum+Number(r.amount||0),0)});style(sheet)});
  const info=workbook.addWorksheet("INFORMATION REQUIRED");info.columns=[{header:"Section",key:"section",width:26},{header:"Work item",key:"item",width:42},{header:"Reason not measured or priced",key:"reason",width:95}];NRM2_INFORMATION_REQUIRED.forEach(item=>info.addRow(item));style(info);
  const trace=workbook.addWorksheet("SOURCE TRACEABILITY");trace.columns=[{header:"BOQ item",key:"item",width:18},{header:"Description",key:"description",width:72},{header:"Source IDs",key:"sources",width:60},{header:"Floors",key:"floors",width:28}];rows.forEach(r=>trace.addRow({item:r.boq_item_number,description:r.description,sources:r.source_ids.join(", "),floors:r.floor_names.join(", ")}));style(trace);
  return workbook.xlsx.writeBuffer();
}
function makePdfBytes(){
  const rows=buildBoqRows();
  const escape=(s:string)=>s.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
  let previousBill="",previousSection="";const wrapped:string[]=[];rows.forEach(r=>{const bill=`BILL ${r.bill_no||"09"} - ${r.bill_name||"OTHER ITEMS"}`;const section=`${r.subcategory_code||"GENERAL"} - ${r.subcategory_name||r.section||"GENERAL"}`;if(bill!==previousBill){wrapped.push("",bill);previousBill=bill;previousSection=""}if(section!==previousSection){wrapped.push(section);previousSection=section}const prefix=`${r.boq_item_number||r.item_code||""} `;const suffix=`  ${r.quantity.toFixed(3)} ${r.unit} @ ${(r.rate||0).toFixed(2)} = ${(r.amount||0).toFixed(2)}`;const width=92-prefix.length-suffix.length;const words=r.description.split(/\s+/);const lines:string[]=[];let current="";for(const word of words){if((current+" "+word).trim().length>width){lines.push(current);current=word}else current=(current+" "+word).trim()}if(current)lines.push(current);wrapped.push(...lines.map((line,i)=>i?`   ${line}`:`${prefix}${line}${suffix}`))});wrapped.push("","INFORMATION REQUIRED - UNMEASURED WORK",...NRM2_INFORMATION_REQUIRED.map(item=>`${item.section}: ${item.item} - ${item.reason}`));
  const chunks:string[][]=[];for(let index=0;index<wrapped.length;index+=38)chunks.push(wrapped.slice(index,index+38));if(!chunks.length)chunks.push(["No confirmed items have been sent to the BOQ."]);
  const objects:string[]=[];const pageIds:number[]=[];const contentIds:number[]=[];const fontId=3+chunks.length*2;chunks.forEach((_,index)=>{pageIds.push(3+index*2);contentIds.push(4+index*2)});objects[1]="<< /Type /Catalog /Pages 2 0 R >>";objects[2]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${chunks.length} >>`;chunks.forEach((lines,index)=>{const page=pageIds[index],contentId=contentIds[index];const pageLines=["QUANTO - BILL OF QUANTITIES",`Page ${index+1} of ${chunks.length}`,"",...lines];let content="BT /F1 9 Tf 36 806 Td ";pageLines.forEach((line,lineIndex)=>{content+=`${lineIndex?"0 -19 Td ":""}(${escape(line)}) Tj `});content+="ET";objects[page]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`});objects[fontId]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  let out="%PDF-1.4\n";const offsets=[0];for(let i=1;i<=fontId;i++){offsets[i]=out.length;out+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${fontId+1}\n0000000000 65535 f \n`;for(let i=1;i<=fontId;i++)out+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;out+=`trailer << /Size ${fontId+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(out);
}
async function makeFormalPdfBytes(){
  const [{jsPDF},{default:autoTable}]=await Promise.all([import("jspdf"),import("jspdf-autotable")]);
  const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const rows=buildBoqRows();const setup=useDemoStore.getState().boqSetup;const currency=setup.currency||"Rs";const money=(value:number)=>`${currency} ${value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  doc.setTextColor(15,23,42);doc.setFont("helvetica","bold");doc.setFontSize(24);doc.text(setup.boq_title||"Bill of Quantities",148.5,55,{align:"center"});doc.setFontSize(16);doc.text(setup.project_name||"Quanto",148.5,68,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(71,85,105);doc.text("Measured and presented in an NRM2-style bill structure",148.5,78,{align:"center"});
  autoTable(doc,{startY:95,margin:{left:58,right:58},theme:"grid",body:[["Client",setup.client_name||"—"],["Consultant",setup.consultant_name||"—"],["Location",setup.location||"—"],["Currency",currency],["Generated",new Date().toLocaleString()]],styles:{fontSize:9,cellPadding:3},columnStyles:{0:{fontStyle:"bold",fillColor:[241,245,249],cellWidth:40},1:{cellWidth:140}}});
  doc.addPage();doc.setFont("helvetica","bold");doc.setFontSize(16);doc.setTextColor(15,23,42);doc.text("Main Summary",14,18);const billKeys=[...new Set(rows.map(row=>`${row.bill_no||"09"}|${row.bill_name||"Other items"}`))];const summaryBody=billKeys.map(key=>{const [bill,name]=key.split("|");const group=rows.filter(row=>String(row.bill_no||"09")===bill);return [bill,name,String(group.length),money(group.reduce((sum,row)=>sum+Number(row.amount||0),0))]});const total=rows.reduce((sum,row)=>sum+Number(row.amount||0),0);summaryBody.push(["","Grand total","",money(total)]);autoTable(doc,{startY:24,head:[["Bill","Description","Items","Amount"]],body:summaryBody,theme:"grid",headStyles:{fillColor:[30,58,138],textColor:255},styles:{fontSize:9,cellPadding:3},columnStyles:{0:{cellWidth:25},1:{cellWidth:165},2:{cellWidth:25,halign:"right"},3:{cellWidth:45,halign:"right"}}});
  for(const key of billKeys){const [bill,name]=key.split("|");const billRows=rows.filter(row=>String(row.bill_no||"09")===bill);doc.addPage();doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text(`Bill ${bill} — ${name}`,14,18);let y=24;const sections=[...new Set(billRows.map(row=>`${row.subcategory_code||"General"}|${row.subcategory_name||row.section||"General"}`))];for(const sectionKey of sections){const [code,sectionName]=sectionKey.split("|");const sectionRows=billRows.filter(row=>`${row.subcategory_code||"General"}|${row.subcategory_name||row.section||"General"}`===sectionKey);if(y>175){doc.addPage();y=18}doc.setFontSize(11);doc.setTextColor(30,58,138);doc.text(`${code} — ${sectionName}`,14,y);autoTable(doc,{startY:y+3,head:[["Item","Description","Unit","Quantity","Rate","Amount"]],body:[...sectionRows.map(row=>[row.boq_item_number||row.item_code||"",row.description,row.unit,row.quantity.toLocaleString(undefined,{maximumFractionDigits:3}),row.rate==null?"":money(row.rate),row.amount==null?"":money(row.amount)]),["","Section subtotal","","","",money(sectionRows.reduce((sum,row)=>sum+Number(row.amount||0),0))]],theme:"grid",headStyles:{fillColor:[226,232,240],textColor:[15,23,42],fontStyle:"bold"},styles:{fontSize:7.5,cellPadding:2,overflow:"linebreak"},columnStyles:{0:{cellWidth:27},1:{cellWidth:145},2:{cellWidth:15},3:{cellWidth:25,halign:"right"},4:{cellWidth:32,halign:"right"},5:{cellWidth:35,halign:"right"}},margin:{left:14,right:14}});y=((doc as unknown as {lastAutoTable?:{finalY:number}}).lastAutoTable?.finalY||y+15)+7}}
  doc.addPage();doc.setFont("helvetica","bold");doc.setFontSize(16);doc.setTextColor(15,23,42);doc.text("Information Required — Unmeasured Work",14,18);autoTable(doc,{startY:24,head:[["Section","Work item","Reason not measured or priced"]],body:NRM2_INFORMATION_REQUIRED.map(item=>[item.section,item.item,item.reason]),theme:"grid",headStyles:{fillColor:[30,58,138],textColor:255},styles:{fontSize:8,cellPadding:3},columnStyles:{0:{cellWidth:45},1:{cellWidth:65},2:{cellWidth:159}}});
  doc.addPage();doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text("Certification",14,18);autoTable(doc,{startY:45,head:[["Prepared by","Checked by","Approved by"]],body:[["\n\nName / signature\nDate","\n\nName / signature\nDate","\n\nName / signature\nDate"]],theme:"grid",styles:{fontSize:9,minCellHeight:28,cellPadding:4},headStyles:{fillColor:[226,232,240],textColor:[15,23,42]}});
  const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(100);if(page>1){doc.text(setup.project_name||"Quanto",14,8);doc.text(setup.boq_title||"Bill of Quantities",283,8,{align:"right"})}doc.text(`Page ${page} of ${pages}`,148.5,202,{align:"center"})}return doc.output("arraybuffer");
}
export async function downloadBoqExport(_projectId:string,exportId:string,filename:string){const exp=useDemoStore.getState().exports.find(e=>e.id===exportId);const format=exp?.format||filename.split('.').pop();if(format==="json")saveBlob(new Blob([JSON.stringify({project:"Quanto",measurement_standard:"RICS NRM2",generated_at:new Date().toISOString(),rows:buildBoqRows(),information_required:NRM2_INFORMATION_REQUIRED},null,2)],{type:"application/json"}),filename);else if(format==="csv")saveBlob(new Blob([makeCsv()],{type:"text/csv;charset=utf-8"}),filename);else if(format==="xlsx")saveBlob(new Blob([await makeXlsx()],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),filename);else saveBlob(new Blob([await makeFormalPdfBytes()],{type:"application/pdf"}),filename);}

export async function selectBoqTemplate(_projectId:string,templateId:string){selectedTemplateId=templateId;return{ok:true};}
export async function getBoqSetup(_projectId:string):Promise<BoqDocumentSetup>{return useDemoStore.getState().boqSetup;}
export async function saveBoqSetup(_projectId:string,payload:BoqDocumentSetup){useDemoStore.getState().updateBoqSetup({...payload,setup_version:payload.setup_version+1});return payload;}
export async function getBoqTemplateLibrary(_projectId:string):Promise<BoqTemplateLibrary>{return{packages:templatePackages,selected_template_id:selectedTemplateId,placeholders:[{key:"type_code",label:"Type code",example:"M01"},{key:"material",label:"Material",example:"Brickwork"}]};}
export async function createBoqTemplatePackage(_projectId:string,payload:{name:string;description?:string;category?:string}):Promise<BoqTemplatePackage>{const t:BoqTemplatePackage={id:`TPL-${Date.now()}`,name:payload.name,description:payload.description||null,category:payload.category||"Custom",version:1,is_default:false,is_builtin:false,is_active:true,items:[]};templatePackages=[...templatePackages,t];return t;}
export async function updateBoqTemplatePackage(_projectId:string,templateId:string,payload:Record<string,unknown>):Promise<BoqTemplatePackage>{let out=templatePackages[0];templatePackages=templatePackages.map(t=>{if(t.id!==templateId)return t;out={...t,...payload} as BoqTemplatePackage;return out});return out;}
export async function duplicateBoqTemplatePackage(_projectId:string,templateId:string,name?:string):Promise<BoqTemplatePackage>{const base=templatePackages.find(t=>t.id===templateId)||templatePackages[0];return createBoqTemplatePackage(_projectId,{name:name||`${base.name} copy`,description:base.description||undefined,category:base.category});}
export async function deleteBoqTemplatePackage(_projectId:string,templateId:string){templatePackages=templatePackages.filter(t=>t.id!==templateId||t.is_builtin);if(selectedTemplateId===templateId)selectedTemplateId=templatePackages[0].id;return{ok:true};}
export async function createBoqTemplateItem(_projectId:string,templateId:string,payload:Omit<BoqTemplateItem,"id"|"template_id">):Promise<BoqTemplateItem>{const item={...payload,id:`TI-${Date.now()}`,template_id:templateId};templatePackages=templatePackages.map(t=>t.id===templateId?{...t,items:[...t.items,item]}:t);return item;}
export async function updateBoqTemplateItem(_projectId:string,templateId:string,itemId:string,payload:Partial<BoqTemplateItem>):Promise<BoqTemplateItem>{let out={} as BoqTemplateItem;templatePackages=templatePackages.map(t=>t.id===templateId?{...t,items:t.items.map(i=>{if(i.id!==itemId)return i;out={...i,...payload};return out})}:t);return out;}
export async function deleteBoqTemplateItem(_projectId:string,templateId:string,itemId:string){templatePackages=templatePackages.map(t=>t.id===templateId?{...t,items:t.items.filter(i=>i.id!==itemId)}:t);return{ok:true};}
export async function previewBoqTemplateItem(_projectId:string,_templateId:string,_itemId:string,_values:Record<string,unknown>={}):Promise<{description:string}>{return{description:"Demo template preview"};}
