export const appRoutes = {
  login: "/sign-in",
  forgotPassword: "/sign-in",
  resetPassword: "/sign-in",
  dashboard: "/projects",
  createProject: "/projects/new",
  upload: "/projects",
  projects: "/projects",
  boqGeneration: "/workspace/demo/pre/upload",
  pdfGeneration: "/workspace/demo/pre/upload",
  workspace: (projectId: string) => `/workspace/${projectId}/pre/upload`,
  pre: (projectId: string, step: string) => `/workspace/${projectId}/pre/${step}`,
  takeoff: (projectId: string, element: string, view: string = "dimension") => `/workspace/${projectId}/takeoff/${element}/${view}`,
  workflowStep: (projectId: string, step: string) => {
    const legacy: Record<string, string> = {
      upload: `/workspace/${projectId}/pre/upload`,
      "floor-plans": `/workspace/${projectId}/pre/plans`,
      specifications: `/workspace/${projectId}/pre/specifications`,
      scale: `/workspace/${projectId}/pre/scale`,
      "model-review": `/workspace/${projectId}/takeoff/doors-windows/dimension`,
      walls: `/workspace/${projectId}/takeoff/walls/dimension`,
      floors: `/workspace/${projectId}/takeoff/floor/dimension`,
      roofs: `/workspace/${projectId}/takeoff/roof/dimension`,
      ceilings: `/workspace/${projectId}/takeoff/ceiling/dimension`,
      review: `/workspace/${projectId}/review`,
      boq: `/workspace/${projectId}/boq`,
    };
    return legacy[step] || `/workspace/${projectId}/${step}`;
  },
  workflowUpload: (projectId: string) => `/workspace/${projectId}/pre/upload`,
  workspaceBoq: (projectId: string) => `/workspace/${projectId}/boq`,
  workspaceReviewTypes: (projectId: string) => `/workspace/${projectId}/review/classifications`,
  workspaceBoqSetup: (projectId: string) => `/workspace/${projectId}/boq/setup`,
  workspaceBoqTemplates: (projectId: string) => `/workspace/${projectId}/boq/templates`,
  workspaceBoqExports: (projectId: string) => `/workspace/${projectId}/boq/exports`,
  admin: "/workspace/demo/pre/upload",
  adminOrganizations: "/workspace/demo/pre/upload",
  adminSuperAdmins: "/workspace/demo/pre/upload",
  adminSubscriptions: "/workspace/demo/pre/upload",
  adminBilling: "/workspace/demo/pre/upload",
  adminAuditLogs: "/workspace/demo/pre/upload",
  adminSettings: "/workspace/demo/pre/upload",
  organization: "/workspace/demo/pre/upload",
  organizationMembers: "/workspace/demo/pre/upload",
  organizationRoles: "/workspace/demo/pre/upload",
  organizationBilling: "/workspace/demo/pre/upload",
  organizationSettings: "/workspace/demo/pre/upload",
  accountProfile: "/workspace/demo/pre/upload",
  accountSettings: "/workspace/demo/pre/upload",
  accountSecurity: "/workspace/demo/pre/upload",
  notifications: "/workspace/demo/pre/upload",
  usage: "/workspace/demo/pre/upload",
};
