"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { Point } from "@/features/demo/types";
import { distance } from "@/features/demo/geometry";
import { svgPoint } from "../components/DemoDrawing";
import { snapMeasurementPoint, type MeasurementMode } from "./measurementGeometry";
import { useMeasurementStore, type DrawingMeasurement } from "./measurementStore";

export function useMeasurementTool({ viewportId, scale, active, deleteEnabled = active, mode = "any" }: { viewportId: string; scale: number; active: boolean; deleteEnabled?: boolean; mode?: MeasurementMode }) {
  const [start, setStart] = useState<Point | null>(null), [previewEnd, setPreviewEnd] = useState<Point | null>(null);
  const altPressed = useRef(false);
  const all = useMeasurementStore((state) => state.measurements), selectedId = useMeasurementStore((state) => state.selectedId), select = useMeasurementStore((state) => state.select), add = useMeasurementStore((state) => state.add), remove = useMeasurementStore((state) => state.remove);
  const measurements = useMemo(() => all.filter((value) => value.viewportId === viewportId), [all, viewportId]);
  const selected = measurements.find((value) => value.id === selectedId) || null, current = selected || measurements.at(-1) || null;
  useEffect(() => { const down = (event: KeyboardEvent) => { if (event.key === "Alt") altPressed.current = true; }, up = (event: KeyboardEvent) => { if (event.key === "Alt") altPressed.current = false; }, reset = () => { altPressed.current = false; }; window.addEventListener("keydown", down); window.addEventListener("keyup", up); window.addEventListener("blur", reset); return () => { window.removeEventListener("keydown", down); window.removeEventListener("keyup", up); window.removeEventListener("blur", reset); }; }, []);
  useEffect(() => { setStart(null); setPreviewEnd(null); }, [viewportId]);
  useEffect(() => { if (!deleteEnabled) return; const key = (event: KeyboardEvent) => { if ((event.key !== "Delete" && event.key !== "Backspace") || !selectedId || (event.target as HTMLElement | null)?.closest("input,textarea,select,[contenteditable='true']")) return; event.preventDefault(); remove(selectedId); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [deleteEnabled, remove, selectedId]);
  function canvasClick(raw: Point) { if (!active) return; if (!start) { setStart(raw); setPreviewEnd(raw); return; } const end = snapMeasurementPoint(start, raw, mode, altPressed.current); if (distance(start, end) > .5) add({ id: `MEASURE-${Date.now()}`, viewportId, start, end }); setStart(null); setPreviewEnd(null); }
  function canvasMove(raw: Point) { if (active && start) setPreviewEnd(snapMeasurementPoint(start, raw, mode, altPressed.current)); }
  return { canvasClick, canvasMove, clearDraft: () => { setStart(null); setPreviewEnd(null); }, clearSelection: () => select(null), start, previewEnd, measurements, selected, current, selectedId, selectedLengthM: current ? distance(current.start, current.end) * scale : null, deleteSelected: () => selected && remove(selected.id), deleteCurrent: () => current && remove(current.id) };
}

export function MeasurementOverlay({ measurements, selectedId, scale, editable, previewStart, previewEnd, color = "#dc2626", onSelectMeasurement }: { measurements: DrawingMeasurement[]; selectedId: string | null; scale: number; editable: boolean; previewStart?: Point | null; previewEnd?: Point | null; color?: string; onSelectMeasurement?: () => void }) {
  const select = useMeasurementStore((state) => state.select);
  return <g>{measurements.map((value) => <EditableMeasurement key={value.id} value={value} selected={selectedId === value.id} scale={scale} editable={editable} color={color} onSelect={() => { select(value.id); onSelectMeasurement?.(); }}/>)}{previewStart && previewEnd ? <Graphic start={previewStart} end={previewEnd} label={format(previewStart, previewEnd, scale)} color={color} preview/> : null}{previewStart && !previewEnd ? <Tick point={previewStart} other={{ x: previewStart.x + 1, y: previewStart.y }} color={color}/> : null}</g>;
}

function EditableMeasurement({ value, selected, scale, editable, color, onSelect }: { value: DrawingMeasurement; selected: boolean; scale: number; editable: boolean; color: string; onSelect: () => void }) {
  const update = useMeasurementStore((state) => state.update);
  const [drag, setDrag] = useState<null | { type: "line" | "start" | "end"; pointerId: number; origin: Point; baseStart: Point; baseEnd: Point; start: Point; end: Point }>(null);
  const shownStart = drag?.start || value.start, shownEnd = drag?.end || value.end;
  function begin(type: "line" | "start" | "end", event: ReactPointerEvent<SVGElement>) { if (!editable) return; const point = svgPoint(event as any); if (!point) return; event.preventDefault(); event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); onSelect(); setDrag({ type, pointerId: event.pointerId, origin: point, baseStart: { ...value.start }, baseEnd: { ...value.end }, start: { ...value.start }, end: { ...value.end } }); }
  function move(event: ReactPointerEvent<SVGElement>) { if (!drag || drag.pointerId !== event.pointerId) return; const point = svgPoint(event as any); if (!point) return; if (drag.type === "line") { const dx = point.x - drag.origin.x, dy = point.y - drag.origin.y, next = { ...drag, start: { x: drag.baseStart.x + dx, y: drag.baseStart.y + dy }, end: { x: drag.baseEnd.x + dx, y: drag.baseEnd.y + dy } }; setDrag(next); update(value.id, { start: next.start, end: next.end }); return; } const anchor = drag.type === "start" ? drag.baseEnd : drag.baseStart, snapped = snapMeasurementPoint(anchor, point, "any", event.altKey), next = drag.type === "start" ? { ...drag, start: snapped } : { ...drag, end: snapped }; setDrag(next); update(value.id, drag.type === "start" ? { start: snapped } : { end: snapped }); }
  const stop = (event: ReactPointerEvent<SVGElement>) => { if (drag?.pointerId === event.pointerId) setDrag(null); };
  return <g onClick={(event) => { event.stopPropagation(); if (editable) onSelect(); }}><Graphic start={shownStart} end={shownEnd} label={format(shownStart, shownEnd, scale)} color={color} selected={selected} onLineDown={(event) => begin("line", event)} onMove={move} onStop={stop}/>{selected && editable ? <><Handle point={shownStart} color={color} onDown={(event) => begin("start", event)} onMove={move} onStop={stop}/><Handle point={shownEnd} color={color} onDown={(event) => begin("end", event)} onMove={move} onStop={stop}/></> : <><Tick point={shownStart} other={shownEnd} color={color}/><Tick point={shownEnd} other={shownStart} color={color}/></>}</g>;
}

function Graphic({ start, end, label, color, selected = false, preview = false, onLineDown, onMove, onStop }: { start: Point; end: Point; label: string; color: string; selected?: boolean; preview?: boolean; onLineDown?: (event: ReactPointerEvent<SVGLineElement>) => void; onMove?: (event: ReactPointerEvent<SVGLineElement>) => void; onStop?: (event: ReactPointerEvent<SVGLineElement>) => void }) { const x = (start.x + end.x) / 2, y = (start.y + end.y) / 2, width = Math.max(84, label.length * 8 + 20); return <g opacity={preview ? .75 : 1}><line x1={start.x} y1={start.y} x2={end.x} y2={end.y} stroke="transparent" strokeWidth={22} vectorEffect="non-scaling-stroke" className={onLineDown ? "cursor-move" : undefined} onPointerDown={onLineDown} onPointerMove={onMove} onPointerUp={onStop} onPointerCancel={onStop}/><line x1={start.x} y1={start.y} x2={end.x} y2={end.y} stroke={color} strokeWidth={selected ? 4 : 3} strokeDasharray={preview ? "7 5" : undefined} vectorEffect="non-scaling-stroke" pointerEvents="none"/><rect x={x - width / 2} y={y - 35} width={width} height={26} rx={8} fill="white" stroke={color} strokeWidth={selected ? 2 : 1} vectorEffect="non-scaling-stroke" pointerEvents="none"/><text x={x} y={y - 17} textAnchor="middle" fontSize={14} fontWeight={800} fill={color} paintOrder="stroke" stroke="white" strokeWidth={3} pointerEvents="none">{label}</text></g>; }
function Tick({ point, other, color }: { point: Point; other: Point; color: string }) { const length = Math.hypot(other.x - point.x, other.y - point.y) || 1, nx = -(other.y - point.y) / length * 6, ny = (other.x - point.x) / length * 6; return <line x1={point.x - nx} y1={point.y - ny} x2={point.x + nx} y2={point.y + ny} stroke={color} strokeWidth={3} vectorEffect="non-scaling-stroke" pointerEvents="none"/>; }
function Handle({ point, color, onDown, onMove, onStop }: { point: Point; color: string; onDown: (event: ReactPointerEvent<SVGRectElement>) => void; onMove: (event: ReactPointerEvent<SVGRectElement>) => void; onStop: (event: ReactPointerEvent<SVGRectElement>) => void }) { return <rect x={point.x - 5} y={point.y - 5} width={10} height={10} rx={1} fill="white" stroke={color} strokeWidth={2.5} vectorEffect="non-scaling-stroke" className="cursor-crosshair" onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onStop} onPointerCancel={onStop}/>; }
const format = (a: Point, b: Point, scale: number) => `${(distance(a, b) * scale).toFixed(2)} m`;
