export type Point = { x: number; y: number };
export type BBox = { x: number; y: number; width: number; height: number };
export type DemoStatus = "ready" | "confirmed" | "needs_review";
export type Sheet = { id:string; sheetNo:string; title:string; revision:string; image:string; page:number; included:boolean };
export type ViewportCategory = "plan"|"elevation"|"section"|"detail"|"schedule";
export type ScaleDistanceUnit = "m" | "cm" | "mm" | "ft-in";
export type ScaleCalibration = { printedScale:string; printedScaleLabel:string; printedEvidenceBox?:[number,number,number,number]; printedEvidenceSource:string; printedEvidenceLocation:string; printedEvidenceKind?:"printed"|"inherited"|"missing"; printedScaleInheritedFrom?:string; x:{line:[number,number,number,number];knownDistanceM:number;label:string;unit?:ScaleDistanceUnit;value?:string}; y:{line:[number,number,number,number];knownDistanceM:number;label:string;unit?:ScaleDistanceUnit;value?:string}; notToScale?:boolean; printedScaleOnly?:boolean };
export type Viewport = { id:string; name:string; category:ViewportCategory; sheetId:string; bbox:[number,number,number,number]; parentViewportId?:string; order?:number; status:DemoStatus; scaleMPerPx?:number; calibration?:ScaleCalibration };
export type Storey = { id:string; name:string; levelIndex:number; factor:number; heightM:number; status:DemoStatus };
export type OpeningFamily = { id:string; parent:"door"|"window"; mark:string; description:string; widthMm:number; heightMm:number; thicknessMm:number; material:string; fittings:string; source:string; color:string };
export type Opening = { id:string; familyId:string; kind:"door"|"window"; floorId:string; viewportId:string; bbox:BBox; hostWallId?:string; status:DemoStatus };
export type FinishFamily = { id:string; kind:"floor"|"ceiling"; mark:string; description:string; material:string; thicknessMm?:number; screed?:string; falls?:string; source:string; color:string };
export type Zone = { id:string; kind:"floor"|"ceiling"; familyId:string; floorId:string; viewportId:string; points:Point[]; deducts:Point[][]; room:string; status:DemoStatus };
export type WallFamily = { id:string; mark:string; description:string; thicknessMm:number; classification:"External"|"Internal"; material:string; color:string };
export type WallFinishFamily = { id:string; mark:string; description:string; material:string; thicknessMm:number; source:string; color:string };
export type Wall = { id:string; familyId:string; floorId:string; viewportId:string; start:Point; end:Point; heightM:number; side1Finish:string; side2Finish:string; status:DemoStatus };
export type RoofFamily = { id:string; mark:string; description:string; layers:string; falls:string; source:string; color:string };
export type UpstandFamily = { id:string; mark:string; description:string; heightMm:number; source:string; color:string };
export type RoofZone = { id:string; familyId:string; upstandFamilyId:string; scope:"Terrace"|"Upper roof"; floorId:string; viewportId:string; points:Point[]; deducts:Point[][]; upstandEdges:boolean[]; status:DemoStatus };
export type HeightRecord = { id:string; name:string; storeyId:string; viewportId:string; yTop:number; yBottom:number; status:DemoStatus };
export type SlabRecord = { id:string; storeyId:string; viewportId:string; topY:number; bottomY:number; x0:number; x1:number; stepX:number; stepOffset:number; status:DemoStatus };
export type SpecificationItem = { id:string; name:string; category:string; viewportId:string; found:boolean; status:DemoStatus; rawText:string; columns?:string[]; rows?:string[][] };
export type ChatEvidence = { label:string; detail?:string; viewportId?:string; entityId?:string };
export type ChatMessage = {
  id:string;
  role:"assistant"|"user";
  text:string;
  entityId?:string;
  questionId?:string;
  evidence?:ChatEvidence[];
  action?:"evidence"|"item";
};
