import type { BBox, DemoStatus, Point } from "@/features/demo/types";

export type SpecialElement="stairs-ramps"|"foundation";

export type FlightFamily={
  id:string;
  mark:string;
  description:string;
  kind:"Stair"|"Ramp";
  widthMm:number;
  riserMm:number;
  treadMm:number;
  waistMm:number;
  landingThicknessMm?:number;
  finish:string;
  treadFinish?:string;
  riserFinish?:string;
  stringFinish?:string;
  rampFinish?:string;
  constructionType?:string;
  material?:string;
  supportCondition?:string;
  concreteProfile?:string;
  source:string;
  color:string;
};
export type RailFamily={id:string;mark:string;description:string;heightMm:number;material?:string;finish?:string;source:string;color:string};
export type StairRampRailSegment={
  rail_id?:string;
  line:Point[];
  host_run_id?:string|null;
  rail_mark?:string|null;
  segment_kind?:"level"|"sloping"|"unknown"|string;
  confidence?:number;
};
export type StairRampComponent={
  component_type:"run"|"landing"|string;
  run_id?:string;
  run_kind?:"stair_flight"|"ramp_run"|string;
  landing_id?:string;
  landing_type?:string;
  polygon?:Point[];
  centerline?:Point[];
  width_px?:number|null;
  visible_riser_count?:number|null;
  visible_tread_count?:number|null;
  include_in_element?:boolean;
};
export type Flight={
  id:string;
  familyId:string;
  railFamilyId:string;
  floorId:string;
  viewportId:string;
  points:Point[];
  voids:Point[][];
  railEdges:boolean[];
  railSegments?:StairRampRailSegment[];
  railEdgesEdited?:boolean;
  components?:StairRampComponent[];
  riseOverrideM?:number;
  evidenceOnly?:boolean;
  linkedFlightId?:string;
  status:DemoStatus;
  kind?:"Stair"|"Ramp";
  typeMark?:string|null;
  startLevelLabel?:string|null;
  endLevelLabel?:string|null;
  widthMm?:number|null;
  riserMm?:number|null;
  treadMm?:number|null;
  waistMm?:number|null;
  landingThicknessMm?:number|null;
  slopeDegrees?:number|null;
  slopePercent?:number|null;
  planAreaM2?:number|null;
  slopingSurfaceAreaM2?:number|null;
  landingAreaM2?:number|null;
  concreteM3?:number|null;
  formworkM2?:number|null;
  treadFinishM2?:number|null;
  riserFinishM2?:number|null;
  stringApronFinishM2?:number|null;
  rampFinishM2?:number|null;
  balustradeLengthM?:number|null;
  flightCount?:number|null;
  riserCount?:number|null;
  treadCount?:number|null;
  quantityStatus?:"ready"|"needs_review"|"information_required"|string;
  reinforcementStatus?:"ready"|"needs_review"|"information_required"|string;
  geometryUserModified?:boolean;
  confidence?:number|null;
};

export type PileFamily={id:string;mark:string;description:string;method:string;diameterMm:number;grade:string;reinforcement:string;source:string;color:string};
export type CapFamily={id:string;mark:string;description:string;widthMm:number;depthMm:number;thicknessMm:number;source:string;color:string};
export type Pile={id:string;familyId:string;floorId:string;viewportId:string;bbox:BBox;hostColumnId?:string;lengthM:number;commencingLevelM:number;toeLevelM:number;status:DemoStatus};
export type PileCap={id:string;familyId:string;floorId:string;viewportId:string;bbox:BBox;hostPileIds:string[];thicknessOverrideMm?:number;status:DemoStatus};
