import type { Point } from "@/features/drawing/types";
import type { FloorDrawing } from "@/features/drawings/types";

export type RoofLevelRole = "main_roof" | "lower_roof" | "roof_terrace" | "roof_deck" | "canopy" | "porch_roof" | "balcony_roof" | "plant_room_roof" | "tank_roof" | "lift_overrun_roof" | "independent_roof";
export type RoofShape = "flat" | "mono_pitch" | "gable" | "hip" | "pyramid_hip" | "intersecting_gable" | "intersecting_hip" | "dutch_gable" | "saltbox" | "gambrel" | "mansard" | "butterfly" | "sawtooth" | "a_frame" | "barrel" | "dome" | "conical" | "canopy" | "porch" | "balcony" | "green_roof" | "glazed_roof" | "unknown";
export type RoofSurfaceClass = "flat_planar" | "sloping_planar" | "curved" | "mesh";
export type RoofSlopeInputMethod = "degrees" | "rise_run" | "percentage";
export type RoofEdgeType = "eave" | "verge" | "rake" | "ridge" | "hip" | "valley" | "abutment" | "parapet" | "upstand" | "downstand" | "internal_angle" | "external_angle" | "gutter" | "valley_gutter" | "internal_gutter" | "channel" | "kerb" | "step" | "roof_step" | "pitch_change" | "level_change" | "unknown_roof_boundary" | "unknown";
export type RoofBoqOwner = "roofs" | "structure" | "ceilings" | "drainage" | "electrical" | "metalwork" | "excluded";

export type RoofLevel = { id: string; project_id: string; host_floor_id?: string | null; host_floor_name?: string | null; name: string; role: RoofLevelRole; roof_type: RoofShape; base_elevation_mm?: number | null; source: string; include_in_boq: boolean; status: string; user_confirmed: boolean; confidence?: number | null; roof_version: number; plane_count: number; unresolved_count: number };
export type RoofRegion = { id: string; roof_level_id: string; host_floor_id?: string | null; name: string; role: RoofLevelRole; geometry: { points: Point[] }; source_drawing_id?: string | null; source_revision_id?: string | null; detection_method: string; status: string; user_confirmed: boolean; confidence?: number | null; plane_count: number };
export type RoofEvidence = { id: string; roof_level_id?: string | null; region_id?: string | null; plane_id?: string | null; evidence_type: string; value: Record<string, unknown>; source_kind: string; source_drawing_id?: string | null; source_revision_id?: string | null; source_page_number?: number | null; source_text?: string | null; confidence?: number | null; status: string };
export type RoofLayer = { id: string; definition_id: string; layer_order: number; layer_type: string; name: string; material?: string | null; thickness_mm?: number | null; nrm_work_section?: string | null; nrm_item?: string | null; measurement_unit: string; separate_boq_item: boolean };
export type RoofDefinition = { id: string; code?: string | null; name: string; description?: string | null; system_type: string; covering_material?: string | null; manufacturer?: string | null; product_code?: string | null; default_waste_percent: number; display_colour: string; status: string; assignment_count: number; layers: RoofLayer[] };
export type RoofPlane = { id: string; roof_level_id: string; region_id?: string | null; name?: string | null; geometry: { points: Point[] }; geometry_source: string; surface_class: RoofSurfaceClass; shape_group: RoofShape; pitch_degrees?: number | null; rise?: number | null; run?: number | null; slope_direction_degrees?: number | null; eave_elevation_mm?: number | null; ridge_elevation_mm?: number | null; projected_area_m2?: number | null; true_area_m2?: number | null; gross_area_m2?: number | null; deduction_area_m2: number; net_area_m2?: number | null; definition_id?: string | null; definition_code?: string | null; definition_name?: string | null; system_type?: string | null; covering_material?: string | null; display_colour?: string | null; include_in_boq: boolean; boq_owner: RoofBoqOwner; status: string; user_confirmed: boolean; confidence?: number | null; roof_version: number };
export type RoofEdge = { id: string; roof_level_id: string; plane_id?: string | null; adjacent_plane_id?: string | null; edge_type: RoofEdgeType; geometry: { points: Point[] }; vertical_difference_m?: number | null; plan_length_m?: number | null; true_length_m?: number | null; definition_id?: string | null; include_in_boq: boolean; boq_owner: RoofBoqOwner; status: string; user_confirmed: boolean; roof_version: number };
export type RoofOpening = { id: string; roof_level_id: string; plane_id: string; opening_type: string; name?: string | null; geometry: { points?: Point[] }; width_mm?: number | null; height_mm?: number | null; quantity: number; area_m2?: number | null; kerb_perimeter_m?: number | null; deduct_from_area: boolean; include_in_boq: boolean; boq_owner: RoofBoqOwner; status: string; user_confirmed: boolean };
export type RoofComponent = { id: string; roof_level_id: string; plane_id?: string | null; component_type: string; category: "feature" | "drainage" | "structure" | "safety" | "edge"; name?: string | null; geometry: { points?: Point[]; point?: Point; quantity?: number; thickness_mm?: number }; measurement_basis: "area" | "length" | "number" | "volume" | "weight"; gross_quantity?: number | null; net_quantity?: number | null; measurement_unit: string; definition_id?: string | null; include_in_boq: boolean; boq_owner: RoofBoqOwner; status: string; user_confirmed: boolean };
export type RoofQuantity = { id: string; roof_level_id: string; plane_id?: string | null; edge_id?: string | null; opening_id?: string | null; component_id?: string | null; quantity_kind: string; roof_level_name: string; net_quantity: number; order_quantity: number; measurement_unit: string; nrm_work_section: string; nrm_item?: string | null; pitch_degrees?: number | null; include_in_boq: boolean; boq_owner: RoofBoqOwner; status: string };
export type RoofDrawing = { host_floor_id: string; host_floor_name: string; architectural_drawing_url?: string | null; roof_drawing_url?: string | null; roof_drawing?: FloorDrawing | null; drawings: FloorDrawing[]; drawing_width: number; drawing_height: number; mm_per_pixel?: number | null; scale_verified: boolean; scale_source?: "inherited" | "drawing" | "required" | "unavailable" };
export type RoofSourceFloor = { id: string; name: string; level_index?: number | null; status?: string | null; has_drawing: boolean; roof_level_id?: string | null; roof_level_count: number; roof_plane_count: number };
export type RoofHistory = { id: string; roof_level_id?: string | null; entity_type: string; entity_id: string; action: string; reason?: string | null; changed_by?: string | null; roof_version: number; created_at: string };
export type RoofDetectionRun = { id: string; host_floor_id?: string | null; status: string; stage: string; progress: number; provider?: string | null; model_id?: string | null; analysis_method?: string | null; created_at?: string | null; completed_at?: string | null; error_code?: string | null; user_message?: string | null; error_message?: string | null; result: Record<string, unknown> };
export type RoofAnalysisConfig = { enabled: boolean; auto_analyze: false; default_quality: "easy" | "medium" | "expert" | "maximum"; json_import_enabled: boolean; prompt_version: string };
export type RoofState = { project: { id: string; name: string }; levels: RoofLevel[]; available_floors: RoofSourceFloor[]; regions: RoofRegion[]; evidence: RoofEvidence[]; detection_runs: RoofDetectionRun[]; selected_floor_id?: string | null; selected_level_id?: string | null; definitions: RoofDefinition[]; planes: RoofPlane[]; edges: RoofEdge[]; openings: RoofOpening[]; components: RoofComponent[]; quantities: RoofQuantity[]; history: RoofHistory[]; drawing?: RoofDrawing | null; analysis: RoofAnalysisConfig; summary: { planes: number; edges: number; openings: number; components: number; confirmed: number; needs_review: number; unassigned: number; projected_area_m2: number; true_area_m2: number; linear_m: number; number: number }; active_jobs: Array<{ id: string; floor_id?: string | null; task_type: string; status: string; progress?: number }>; can_continue: boolean };
export type RoofPlanePayload = Partial<Pick<RoofPlane, "name" | "surface_class" | "shape_group" | "pitch_degrees" | "rise" | "run" | "slope_direction_degrees" | "eave_elevation_mm" | "ridge_elevation_mm" | "definition_id" | "include_in_boq" | "boq_owner">> & { points?: Point[] };
