import type { Centerline } from "./types";
import type { FloorDrawing } from "@/features/drawings/types";

export type WallFinishDefinition = {
  id: string;
  original_tag: string | null;
  name: string;
  description: string | null;
  material_category: string | null;
  material: string | null;
  manufacturer: string | null;
  product_code: string | null;
  colour: string | null;
  display_colour: string;
  width_mm: number | null;
  height_mm: number | null;
  thickness_mm: number | null;
  surface_finish: string | null;
  pattern: string | null;
  installation_direction: string | null;
  substrate: string | null;
  preparation: string | null;
  primer: string | null;
  adhesive: string | null;
  grout: string | null;
  joint_size_mm: number | null;
  coat_count: number | null;
  coverage_m2_per_litre: number | null;
  default_waste_percent: number;
  nrm2_work_section: "28" | "29";
  assignment_count: number;
  layers: Array<{ id: string; layer_type: string; name: string; measurement_unit: string }>;
  graphic_signatures?: Array<{ id: string; signature_type: string; signature: Record<string, unknown>; confidence?: number | null }>;
};

export type WallFinishEvidence = {
  id: string;
  evidence_type: string;
  value_text: string | null;
  source_file_name: string | null;
  source_page: number | null;
  source_text: string | null;
  confidence: number | null;
  priority: number;
  accepted: boolean;
};

export type WallFinishZone = {
  id: string;
  wall_face_id: string;
  friendly_number: string | null;
  name: string | null;
  zone_type: "background" | "feature" | string;
  polygon_xz: Array<{ x: number; z: number }>;
  from_x_mm: number | null;
  to_x_mm: number | null;
  from_z_mm: number | null;
  to_z_mm: number | null;
  gross_area_m2: number | null;
  opening_deduction_m2: number;
  excluded_area_m2: number;
  net_area_m2: number | null;
  status: string;
  assignment_id: string | null;
  finish_id: string | null;
  assignment_status: string | null;
  assignment_method: string | null;
  assignment_confirmed: boolean;
  confidence: number | null;
  waste_percent: number;
  order_area_m2: number | null;
  tile_count: number | null;
  primer_litres: number | null;
  finish_litres: number | null;
  wallpaper_rolls: number | null;
  finish_code: string | null;
  finish_name: string | null;
  finish_description: string | null;
  material_category: string | null;
  material: string | null;
  display_colour: string | null;
  evidence: WallFinishEvidence[];
};

export type WallFace = {
  id: string;
  project_id: string;
  floor_id: string;
  wall_id: string;
  source_element_id: string | null;
  model_item_number: number | null;
  model_element_excluded: boolean | number | null;
  model_geometry: { x: number; y: number; width: number; height: number; rotation?: number } | null;
  side_code: "A" | "B";
  friendly_number: string;
  adjacent_room_id: string | null;
  adjacent_room_name: string | null;
  adjacent_room_number: string | null;
  adjacent_space: string | null;
  room_type: string | null;
  room_relative_direction: string | null;
  line: Centerline;
  profile_xz: { points: Array<{ x: number; z: number }> };
  gross_area_m2: number | null;
  length_mm: number | null;
  height_mm: number | null;
  status: string;
  zones: WallFinishZone[];
};

export type WallFinishFloor = {
  id: string;
  name: string;
  level_index: number;
  wall_finish_version: number;
  plan_north_degrees: number;
  direction_status: string;
  drawing_url: string | null;
  architectural_drawing_url: string | null;
  wall_finish_drawing_url: string | null;
  finish_drawings: FloorDrawing[];
  drawing_width: number;
  drawing_height: number;
};

export type WallFinishState = {
  project: { id: string; name: string };
  floors: WallFinishFloor[];
  selected_floor_id: string | null;
  definitions: WallFinishDefinition[];
  faces: WallFace[];
  zones: WallFinishZone[];
  summary: { total: number; confirmed: number; needs_review: number; conflicts: number; unassigned: number; area_m2: number };
  active_jobs: Array<{ id: string; task_type: string; status: string }>;
  needs_automatic_sync: boolean;
  can_continue: boolean;
};

export type WallFinishDefinitionPayload = {
  original_tag?: string | null;
  name: string;
  description?: string | null;
  material_category?: string | null;
  material?: string | null;
  manufacturer?: string | null;
  product_code?: string | null;
  colour?: string | null;
  display_colour?: string | null;
  width_mm?: number | null;
  height_mm?: number | null;
  thickness_mm?: number | null;
  surface_finish?: string | null;
  pattern?: string | null;
  installation_direction?: string | null;
  substrate?: string | null;
  preparation?: string | null;
  primer?: string | null;
  adhesive?: string | null;
  grout?: string | null;
  joint_size_mm?: number | null;
  coat_count?: number | null;
  coverage_m2_per_litre?: number | null;
  default_waste_percent?: number;
  nrm2_work_section?: "28" | "29" | null;
};
